### ISSUE TITLE
How to Pass Prompt Template Without Retriever in neo4j_graphrag for Multi-Step LLM Workflow

### ISSUE THREAD

**Issue by naveen-420** [neo4j/neo4j-graphrag-python#188]
Hi Team,

I'm working on creating a multi-step LLM application. In the first step, the LLM uses a retriever to generate output. However, in the second step, I do not want to use a retriever, but instead provide a prompt template directly to the LLM to generate the correct response.

I know how to pass a prompt template when using a retriever, like this:
```

python

GraphRAG(retriever=retriever, llm=llm, prompt_template=prompt_template)
```

But I've noticed that the retriever is a required field in GraphRAG. Since I don't want to use a retriever for the second step and only pass a prompt template to the LLM, how can I achieve this?

Is it possible with the neo4j_graphrag package, or should I consider using LangChain to accomplish this?

Thank you!

**Comment by stellasia** [comment]
Hi @naveen-420 ,

If I understood properly, in your second step you just need to call an LLM, so you can use `llm.invoke(input="...")` (or `llm.ainvoke(input="...")` for the async version).

**Comment by naveen-420** [comment]
> Hi @naveen-420 ,
> 
> If I understood properly, in your second step you just need to call an LLM, so you can use `llm.invoke(input="...")` (or `llm.ainvoke(input="...")` for the async version).

@stellasia Thank you for the response! Yes, you're right. In the second step, I just need to call the LLM without a retriever.

However, my goal is to use a custom prompt template with llm.invoke() instead of just providing raw input. In the first step, I’m able to pass the prompt_template while using the retriever with GraphRAG. But in the second step, without a retriever, I still want to structure the LLM’s input using a prompt template.

Is there a way to pass a prompt_template directly to llm.invoke() (or llm.ainvoke()), or would I need to manually format the prompt before invoking the LLM?

Thanks again for your help!

**Comment by stellasia** [comment]
You'll have to manually format the prompt, our LLM interface only takes a text and returns a text.

**Comment by naveen-420** [comment]
Ok. Thank you @stellasia
