### ISSUE TITLE
Support for Ollama

### ISSUE THREAD

**Issue by ninjalu** [neo4j/neo4j-graphrag-python#194]
Do you support Ollama llms and embeddings for kg_builder.

At a glance it looks like the embedder could be swapped out easily with an Ollama embedder, not sure how llm work with KG pipeline? Could you advise?

**Comment by stellasia** [comment]
Hi @ninjalu ,

Yes `Ollama` is supported through the `OpenAI` classes. See [this example](https://github.com/neo4j/neo4j-graphrag-python/blob/main/examples/customize/embeddings/ollama_embeddings.py) for embeddings. 

I realize we do not have such example for LLM, but it's the same idea, you instantiate an `OpenAILLM` with `base_url="http://localhost:11434/v1"`.

Let me know if you need more details.

**Comment by ninjalu** [comment]
Thanks.

I got am still having some connection issues:

> neo4j_graphrag/llm/openai_llm.py", line 109, in ainvoke
>     raise LLMGenerationError(e)
> neo4j_graphrag.exceptions.LLMGenerationError: Connection error.

running `asyncio.run(kg_builder.run_async(text=text))`
with these setup
```api_key = "ollama"
ollma_url = "http://127.0.0.1:11434/v1"
embedder = OpenAIEmbeddings(
    base_url=ollma_url, api_key=api_key, model="nomic-embed-text"
)

llm = OpenAILLM(base_url=ollma_url, model_name="llama3.2", api_key=api_key)```
Could you advise please? Thanks!

Running Neo4j5.21.0 locally with apoc

**Comment by stellasia** [comment]
Hi @ninjalu ,

Were you able to make it work? If so, please close the issue. Thank you.

**Comment by ninjalu** [comment]
Hey, thanks Stella. I haven't been able to find time to work on this. I will close this now, and reopen if I have further questions. Many thanks for your help!
