### ISSUE TITLE
Import "neo4j_graphrag.experimental.components.lexical_graph" could not be resolved

### ISSUE THREAD

**Issue by letoribo** [neo4j/neo4j-graphrag-python#204]
![image](https://github.com/user-attachments/assets/0f93f6f3-1abc-44b3-a93a-a4fbd7a62ba4)

**Comment by letoribo** [comment]
Also, after neo4j_graphrag/experimental/components/lexical_graph.py was manually created I encountered another error:

```
    from neo4j_graphrag.experimental.components.lexical_graph import LexicalGraphBuilder
  File "/home/atman/.local/lib/python3.10/site-packages/neo4j_graphrag/experimental/components/lexical_graph.py", line 22, in <module>
    from neo4j_graphrag.experimental.components.types import (
ImportError: cannot import name 'GraphResult' from 'neo4j_graphrag.experimental.components.types' (/home/atman/.local/lib/python3.10/site-packages/neo4j_graphrag/experimental/components/types.py)
```

**Comment by letoribo** [comment]
After copy/pasting neo4j_graphrag/experimental/components/types.py file content the error disappeared

**Comment by letoribo** [comment]
And below error when running `main(driver)`
```
File "/home/pgi-b/api/lexical_graph_builder_from_text.py", line 80, in main
    return await pipe.run(pipe_inputs)
  File "/home/atman/.local/lib/python3.10/site-packages/neo4j_graphrag/experimental/pipeline/pipeline.py", line 610, in run
    self.validate_input_data(data)
  File "/home/atman/.local/lib/python3.10/site-packages/neo4j_graphrag/experimental/pipeline/pipeline.py", line 520, in validate_input_data
    self.validate_parameter_mapping()
  File "/home/atman/.local/lib/python3.10/site-packages/neo4j_graphrag/experimental/pipeline/pipeline.py", line 503, in validate_parameter_mapping
    self.validate_parameter_mapping_for_task(task)
  File "/home/atman/.local/lib/python3.10/site-packages/neo4j_graphrag/experimental/pipeline/pipeline.py", line 569, in validate_parameter_mapping_for_task
    raise PipelineDefinitionError(
graphql.error.graphql_error.GraphQLError: Parameter 'lexical_graph_config' is not a valid input for component 'writer' of type 'Neo4jWriter'
```

**Comment by letoribo** [comment]
After updating the content of neo4j_graphrag/experimental/components/kg_writer.py:
`    from .lexical_graph_builder_from_text import main
  File "/home/pgi-b/api/lexical_graph_builder_from_text.py", line 9, in <module>
    from neo4j_graphrag.experimental.components.kg_writer import Neo4jWriter
  File "/home/atman/.local/lib/python3.10/site-packages/neo4j_graphrag/experimental/components/kg_writer.py", line 31, in <module>
    from neo4j_graphrag.neo4j_queries import (
ImportError: cannot import name 'UPSERT_NODE_QUERY_VARIABLE_SCOPE_CLAUSE' from 'neo4j_graphrag.neo4j_queries' (/home/atman/.local/lib/python3.10/site-packages/neo4j_graphrag/neo4j_queries.py)`

**Comment by letoribo** [comment]
Updating the content of the `neo4j_graphrag/neo4j_queries.py` removed this error

**Comment by letoribo** [comment]
![image](https://github.com/user-attachments/assets/272c10c5-6325-4305-b774-3c0a34a08eb1)

**Comment by letoribo** [comment]
Building KG using SimpleKGPipeline from the same text indeed gives more simple result:
![image](https://github.com/user-attachments/assets/df99e747-bf01-4756-a4bc-18fa3f9b8752)

**Comment by stellasia** [comment]
Hi @letoribo , 

If you copied the example file alone, it doesn't work yet with the latest released version, but it works with the main branch (we're planning a new release soon).

Regarding the difference between the two result graphs:
- If you build only the lexical graph , you will have only the document and "chunks" node.  In the example we are using, the chunks are labelled `TextPart` to demo how to customize the labels. But no entity or relation are extracted. Also, we use a very small chunk size (20), because the text we use in the example is quite small.
- In the SimpleKGPipeline, by default we use the default parameters for chunking, which are much higher (chunk_size=4000), so you see less `Chunk` nodes, and we perform entity and relation extraction, so this is why you see other labels such as `Person`.
