### ISSUE TITLE
cypher execution read/write control

### ISSUE THREAD

**Issue by ruiguo-bio** [neo4j/neo4j-graphrag-python#210]
The current implementation of text2cypher.py:

` records, _, _ = self.driver.execute_query(query_=t2c_query)`
Now the read/write permission can not be passed from outside that function. Need a parameter to pass that for that control.

**Comment by willtai** [comment]
Just to clarify, do you want this `routing` parameter exposed?

**Comment by ruiguo-bio** [comment]
Yes that's what I want.

Thanks.

Best

**Comment by stellasia** [comment]
Hi @ruiguo-bio , 

In the last release ([1.2.1](https://github.com/neo4j/neo4j-graphrag-python/releases/tag/1.2.1)), the routing is forced to `READ` in all retrievers. Let us know if you have a use case that requires changing it.

**Comment by stellasia** [comment]
Closing this as I think the underlying issue was addressed by #217 and released in 1.2.1. Feel free to reopen if not.
