### ISSUE TITLE
Document node not created in lexical graph

### ISSUE THREAD

**Issue by jekeuter** [neo4j/neo4j-graphrag-python#211]
Running this [simple example on building the graph based on text](https://github.com/neo4j/neo4j-graphrag-python?tab=readme-ov-file#knowledge-graph-construction) I am constantly receiving the following issue:

`UserWarning: No document metadata provided, the document node won't be created in the lexical graph`

It creates all other nodes and processes the rest of the steps of the pipeline successfully.

**Any fix to that?**

I am operating on a basis Aura BD, APOC Core library is enabled

**Comment by stellasia** [comment]
Hi @jekeuter , 

There is no "fix" at the moment for this warning, the `SimpleKGPipeline` does not create a document when run with text input (it does when run with [PDF input](https://github.com/neo4j/neo4j-graphrag-python/blob/main/examples/build_graph/simple_kg_builder_from_pdf.py)).

We can improve doc and maybe suppress this warning. I'm wondering, how annoying is it for your use case not to have the document node in the db?

Thank you.

**Comment by stellasia** [comment]
The misleading warning was removed in [1.2.1](https://github.com/neo4j/neo4j-graphrag-python/releases/tag/1.2.1).

I'm closing this issue, feel free to reopen if I misunderstood something.
