### ISSUE TITLE
[Enhancement] Custom embeddings or local model embeddings

### ISSUE THREAD

**Issue by msenechal** [neo4j/neo4j-graphrag-python#219]
Would be cool to have a CustomEmbeddings and/or OllamaEmbeddings in our graphrag lib [in here](https://github.com/neo4j/neo4j-graphrag-python/tree/main/src/neo4j_graphrag/embeddings) so that it align with the rest of the lib since we provide [custom LLMs interface](https://neo4j.com/docs/neo4j-graphrag-python/current/user_guide_rag.html#using-a-custom-model)
Use case is for customer using local models and who don't want to use openAI/vertexAI for generating the embeddings

**Comment by stellasia** [comment]
Hi Morgan,

Thanks for the feedback.

We support Ollama models through the OpenAILLM class. Check the example [here](https://github.com/neo4j/neo4j-graphrag-python/blob/main/examples/customize/embeddings/ollama_embeddings.py). It is documented [here](https://neo4j.com/docs/neo4j-graphrag-python/current/user_guide_rag.html#using-a-local-model-via-ollama).

Do you think something else need to be added?

**Comment by stellasia** [comment]
No worries, it's not the first request we got regarding this, so it's probably not very clear. Adding a special wrapper class could be a solution to improve visibility on this feature, but maybe we can first try to focus on improving the documentation.

**Comment by stellasia** [comment]
Hi Morgan,

In the brand new 1.3.0 release, you'll find `OllamaLLM` and `OllamaEmbeddings` clases. You'll have to install the `ollama` python package for them to work.
