### ISSUE TITLE
AzureOpenAIEmbeddings with headers

### ISSUE THREAD

**Issue by bucioo** [neo4j/neo4j-graphrag-python#227]
Hi,

i need to use proxy to connect to Azure OpenAI and it requires to authenticate with api_key as a Bearer token. I've tried like that:

```
embedder = AzureOpenAIEmbeddings(
    model="text-embedding-ada-002",
    base_url="https://<proxy>",
    api_version=api_version,
    api_key=api_key,
    headers=custom_headers()
)
```

but it doesn't work as not accepting additional 'headers'
'custom_headers' are set to {"Authorization": f"Bearer {api_key}}

Any ideas how it can be done?

Regards,
Bartosz

**Comment by stellasia** [comment]
Hi @bucioo ,

Our package acts as a wrapper around the `openai.AzureOpenAI` client. Maybe you can try using `default_headers`?

See [here](https://github.com/openai/openai-python/blob/ea049cd0c42e115b90f1b9c7db80b2659a0bb92a/src/openai/lib/azure.py#L81).

**Comment by bucioo** [comment]
Hi,

that worked well, thank you!

Regards
